# Recipe configuration
recipe:
  top: GOLD_INGOT
  middle: DIAMOND_BLOCK
  center: ENDER_PEARL

# Teleporter storage (don't edit manually)
teleporters: {}

# Home storage (don't edit manually)
homes: {}

