name: ManagePlugin
main: com.etrigan.managePlugin.ManagePlugin
version: 0.2
api-version: 1.21.3
commands:
  sethome:
    description: Set your home location
    usage: /<command>
  home:
    description: Teleport to your home location
    usage: /<command>